version: '3.7'
services:
  web:
    build: .
    image: xd
    container_name: web
    volumes:
      - ./:/var/www/html
      - ./tmp/docker-xdebug:/tmp/docker-xdebug
    ports:
      - "80:80"
    environment:
      - XDEBUG_MODE=${XDEBUG_MODE}
